export const phoneCodes: {
  label: string;
  value: string;
  flag: string;
  code: string;
  name: string;
}[] = [
  ...(process.env.NEXT_PUBLIC_NODE_ENV !== "production"
    ? [
        {
          label: "+380",
          value: "+380",
          code: "UA",
          flag: "https://cdn.kcak11.com/CountryFlags/countries/ua.svg",
          name: "Ukraine",
        },
      ]
    : []),
  {
    label: "+213",
    value: "+213",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/dz.svg",
    code: "DZ",
    name: "Algeria",
  },
  {
    label: "+1684",
    value: "+1684",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/as.svg",
    code: "AS",
    name: "AmericanSamoa",
  },
  {
    label: "+376",
    value: "+376",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ad.svg",
    code: "AD",
    name: "Andorra",
  },
  {
    label: "+1268",
    value: "+1268",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ag.svg",
    code: "AG",
    name: "Antigua and Barbuda",
  },
  {
    label: "+54",
    value: "+54",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ar.svg",
    code: "AR",
    name: "Argentina",
  },
  {
    label: "+374",
    value: "+374",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/am.svg",
    code: "AM",
    name: "Armenia",
  },
  {
    label: "+297",
    value: "+297",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/aw.svg",
    code: "AW",
    name: "Aruba",
  },
  {
    label: "+61",
    value: "+61",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/au.svg",
    code: "AU",
    name: "Australia",
  },
  {
    label: "+43",
    value: "+43",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/at.svg",
    code: "AT",
    name: "Austria",
  },
  {
    label: "+994",
    value: "+994",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/az.svg",
    code: "AZ",
    name: "Azerbaijan",
  },
  {
    label: "+973",
    value: "+973",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/bh.svg",
    code: "BH",
    name: "Bahrain",
  },
  {
    label: "+1246",
    value: "+1246",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/bb.svg",
    code: "BB",
    name: "Barbados",
  },
  {
    label: "+32",
    value: "+32",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/be.svg",
    code: "BE",
    name: "Belgium",
  },
  {
    label: "+501",
    value: "+501",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/bz.svg",
    code: "BZ",
    name: "Belize",
  },
  {
    label: "+229",
    value: "+229",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/bj.svg",
    code: "BJ",
    name: "Benin",
  },
  {
    label: "+1441",
    value: "+1441",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/bm.svg",
    code: "BM",
    name: "Bermuda",
  },
  {
    label: "+975",
    value: "+975",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/bt.svg",
    code: "BT",
    name: "Bhutan",
  },
  {
    label: "+387",
    value: "+387",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ba.svg",
    code: "BA",
    name: "Bosnia and Herzegovina",
  },
  {
    label: "+55",
    value: "+55",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/br.svg",
    code: "BR",
    name: "Brazil",
  },
  {
    label: "+673",
    value: "+673",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/bn.svg",
    code: "BN",
    name: "Brunei Darussalam",
  },
  {
    label: "+359",
    value: "+359",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/bg.svg",
    code: "BG",
    name: "Bulgaria",
  },
  {
    label: "+226",
    value: "+226",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/bf.svg",
    code: "BF",
    name: "Burkina Faso",
  },
  {
    label: "+257",
    value: "+257",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/bi.svg",
    code: "BI",
    name: "Burundi",
  },
  {
    label: "+855",
    value: "+855",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/kh.svg",
    code: "KH",
    name: "Cambodia",
  },
  {
    label: "+237",
    value: "+237",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/cm.svg",
    code: "CM",
    name: "Cameroon",
  },
  {
    label: "+1",
    value: "+1",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ca.svg",
    code: "CA",
    name: "Canada",
  },
  {
    label: "+238",
    value: "+238",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/cv.svg",
    code: "CV",
    name: "Cape Verde",
  },
  {
    label: "+345",
    value: "+345",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ky.svg",
    code: "KY",
    name: "Cayman Islands",
  },
  {
    label: "+56",
    value: "+56",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/cl.svg",
    code: "CL",
    name: "Chile",
  },
  {
    label: "+86",
    value: "+86",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/cn.svg",
    code: "CN",
    name: "China",
  },
  {
    label: "+57",
    value: "+57",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/co.svg",
    code: "CO",
    name: "Colombia",
  },
  {
    label: "+682",
    value: "+682",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ck.svg",
    code: "CK",
    name: "Cook Islands",
  },
  {
    label: "+506",
    value: "+506",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/cr.svg",
    code: "CR",
    name: "Costa Rica",
  },
  {
    label: "+225",
    value: "+225",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ci.svg",
    code: "CI",
    name: "Cote d'Ivoire",
  },
  {
    label: "+385",
    value: "+385",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/hr.svg",
    code: "HR",
    name: "Croatia",
  },
  {
    label: "+53",
    value: "+53",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/cu.svg",
    code: "CU",
    name: "Cuba",
  },
  {
    label: "+537",
    value: "+537",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/cy.svg",
    code: "CY",
    name: "Cyprus",
  },
  {
    label: "+420",
    value: "+420",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/cz.svg",
    code: "CZ",
    name: "Czech Republic",
  },
  {
    label: "+45",
    value: "+45",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/dk.svg",
    code: "DK",
    name: "Denmark",
  },
  {
    label: "+253",
    value: "+253",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/dj.svg",
    code: "DJ",
    name: "Djibouti",
  },
  {
    label: "+1767",
    value: "+1767",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/dm.svg",
    code: "DM",
    name: "Dominica",
  },
  {
    label: "+1849",
    value: "+1849",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/do.svg",
    code: "DO",
    name: "Dominican Republic",
  },
  {
    label: "+593",
    value: "+593",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ec.svg",
    code: "EC",
    name: "Ecuador",
  },
  {
    label: "+20",
    value: "+20",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/eg.svg",
    code: "EG",
    name: "Egypt",
  },
  {
    label: "+503",
    value: "+503",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/sv.svg",
    code: "SV",
    name: "El Salvador",
  },
  {
    label: "+240",
    value: "+240",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/gq.svg",
    code: "GQ",
    name: "Equatorial Guinea",
  },
  {
    label: "+372",
    value: "+372",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ee.svg",
    code: "EE",
    name: "Estonia",
  },
  {
    label: "+251",
    value: "+251",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/et.svg",
    code: "ET",
    name: "Ethiopia",
  },
  {
    label: "+298",
    value: "+298",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/fo.svg",
    code: "FO",
    name: "Faroe Islands",
  },
  {
    label: "+679",
    value: "+679",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/fj.svg",
    code: "FJ",
    name: "Fiji",
  },
  {
    label: "+358",
    value: "+358",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/fi.svg",
    code: "FI",
    name: "Finland",
  },
  {
    label: "+33",
    value: "+33",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/fr.svg",
    code: "FR",
    name: "France",
  },
  {
    label: "+241",
    value: "+241",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ga.svg",
    code: "GA",
    name: "Gabon",
  },
  {
    label: "+995",
    value: "+995",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ge.svg",
    code: "GE",
    name: "Georgia",
  },
  {
    label: "+49",
    value: "+49",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/de.svg",
    code: "DE",
    name: "Germany",
  },
  {
    label: "+350",
    value: "+350",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/gi.svg",
    code: "GI",
    name: "Gibraltar",
  },
  {
    label: "+30",
    value: "+30",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/gr.svg",
    code: "GR",
    name: "Greece",
  },
  {
    label: "+1473",
    value: "+1473",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/gd.svg",
    code: "GD",
    name: "Grenada",
  },
  {
    label: "+502",
    value: "+502",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/gt.svg",
    code: "GT",
    name: "Guatemala",
  },
  {
    label: "+44",
    value: "+44",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/gg.svg",
    code: "GG",
    name: "Guernsey",
  },
  {
    label: "+224",
    value: "+224",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/gn.svg",
    code: "GN",
    name: "Guinea",
  },
  {
    label: "+504",
    value: "+504",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/hn.svg",
    code: "HN",
    name: "Honduras",
  },
  {
    label: "+852",
    value: "+852",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/hk.svg",
    code: "HK",
    name: "Hong Kong",
  },
  {
    label: "+36",
    value: "+36",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/hu.svg",
    code: "HU",
    name: "Hungary",
  },
  {
    label: "+354",
    value: "+354",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/is.svg",
    code: "IS",
    name: "Iceland",
  },
  {
    label: "+91",
    value: "+91",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/in.svg",
    code: "IN",
    name: "India",
  },
  {
    label: "+62",
    value: "+62",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/id.svg",
    code: "ID",
    name: "Indonesia",
  },
  {
    label: "+353",
    value: "+353",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ie.svg",
    code: "IE",
    name: "Ireland",
  },
  {
    label: "+44",
    value: "+44",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/im.svg",
    code: "IM",
    name: "Isle of Man",
  },
  {
    label: "+972",
    value: "+972",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/il.svg",
    code: "IL",
    name: "Israel",
  },
  {
    label: "+39",
    value: "+39",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/it.svg",
    code: "IT",
    name: "Italy",
  },
  {
    label: "+1876",
    value: "+1876",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/jm.svg",
    code: "JM",
    name: "Jamaica",
  },
  {
    label: "+81",
    value: "+81",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/jp.svg",
    code: "JP",
    name: "Japan",
  },
  {
    label: "+44",
    value: "+44",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/je.svg",
    code: "JE",
    name: "Jersey",
  },
  {
    label: "+77",
    value: "+77",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/kz.svg",
    code: "KZ",
    name: "Kazakhstan",
  },
  {
    label: "+254",
    value: "+254",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ke.svg",
    code: "KE",
    name: "Kenya",
  },
  {
    label: "+965",
    value: "+965",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/kw.svg",
    code: "KW",
    name: "Kuwait",
  },
  {
    label: "+996",
    value: "+996",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/kg.svg",
    code: "KG",
    name: "Kyrgyzstan",
  },
  {
    label: "+371",
    value: "+371",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/lv.svg",
    code: "LV",
    name: "Latvia",
  },
  {
    label: "+961",
    value: "+961",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/lb.svg",
    code: "LB",
    name: "Lebanon",
  },
  {
    label: "+266",
    value: "+266",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ls.svg",
    code: "LS",
    name: "Lesotho",
  },
  {
    label: "+218",
    value: "+218",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ly.svg",
    code: "LY",
    name: "Libyan Arab Jamahiriya",
  },
  {
    label: "+423",
    value: "+423",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/li.svg",
    code: "LI",
    name: "Liechtenstein",
  },
  {
    label: "+370",
    value: "+370",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/lt.svg",
    code: "LT",
    name: "Lithuania",
  },
  {
    label: "+352",
    value: "+352",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/lu.svg",
    code: "LU",
    name: "Luxembourg",
  },
  {
    label: "+389",
    value: "+389",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/mk.svg",
    code: "MK",
    name: "Macedonia, The Former Yugoslav Republic of",
  },
  {
    label: "+265",
    value: "+265",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/mw.svg",
    code: "MW",
    name: "Malawi",
  },
  {
    label: "+60",
    value: "+60",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/my.svg",
    code: "MY",
    name: "Malaysia",
  },
  {
    label: "+356",
    value: "+356",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/mt.svg",
    code: "MT",
    name: "Malta",
  },
  {
    label: "+222",
    value: "+222",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/mr.svg",
    code: "MR",
    name: "Mauritania",
  },
  {
    label: "+52",
    value: "+52",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/mx.svg",
    code: "MX",
    name: "Mexico",
  },
  {
    label: "+373",
    value: "+373",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/md.svg",
    code: "MD",
    name: "Moldova, Republic of",
  },
  {
    label: "+377",
    value: "+377",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/mc.svg",
    code: "MC",
    name: "Monaco",
  },
  {
    label: "+382",
    value: "+382",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/me.svg",
    code: "ME",
    name: "Montenegro",
  },
  {
    label: "+1664",
    value: "+1664",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ms.svg",
    code: "MS",
    name: "Montserrat",
  },
  {
    label: "+212",
    value: "+212",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ma.svg",
    code: "MA",
    name: "Morocco",
  },
  {
    label: "+264",
    value: "+264",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/na.svg",
    code: "NA",
    name: "Namibia",
  },
  {
    label: "+977",
    value: "+977",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/np.svg",
    code: "NP",
    name: "Nepal",
  },
  {
    label: "+31",
    value: "+31",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/nl.svg",
    code: "NL",
    name: "Netherlands",
  },
  {
    label: "+599",
    value: "+599",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/an.svg",
    code: "AN",
    name: "Netherlands Antilles",
  },
  {
    label: "+64",
    value: "+64",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/nz.svg",
    code: "NZ",
    name: "New Zealand",
  },
  {
    label: "+505",
    value: "+505",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ni.svg",
    code: "NI",
    name: "Nicaragua",
  },
  {
    label: "+227",
    value: "+227",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ne.svg",
    code: "NE",
    name: "Niger",
  },
  {
    label: "+234",
    value: "+234",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ng.svg",
    code: "NG",
    name: "Nigeria",
  },
  {
    label: "+672",
    value: "+672",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/nf.svg",
    code: "NF",
    name: "Norfolk Island",
  },
  {
    label: "+47",
    value: "+47",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/no.svg",
    code: "NO",
    name: "Norway",
  },
  {
    label: "+968",
    value: "+968",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/om.svg",
    code: "OM",
    name: "Oman",
  },
  {
    label: "+92",
    value: "+92",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/pk.svg",
    code: "PK",
    name: "Pakistan",
  },
  {
    label: "+970",
    value: "+970",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ps.svg",
    code: "PS",
    name: "Palestinian Territory, Occupied",
  },
  {
    label: "+507",
    value: "+507",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/pa.svg",
    code: "PA",
    name: "Panama",
  },
  {
    label: "+595",
    value: "+595",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/py.svg",
    code: "PY",
    name: "Paraguay",
  },
  {
    label: "+51",
    value: "+51",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/pe.svg",
    code: "PE",
    name: "Peru",
  },
  {
    label: "+63",
    value: "+63",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ph.svg",
    code: "PH",
    name: "Philippines",
  },
  {
    label: "+48",
    value: "+48",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/pl.svg",
    code: "PL",
    name: "Poland",
  },
  {
    label: "+351",
    value: "+351",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/pt.svg",
    code: "PT",
    name: "Portugal",
  },
  {
    label: "+1939",
    value: "+1939",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/pr.svg",
    code: "PR",
    name: "Puerto Rico",
  },
  {
    label: "+974",
    value: "+974",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/qa.svg",
    code: "QA",
    name: "Qatar",
  },
  {
    label: "+40",
    value: "+40",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ro.svg",
    code: "RO",
    name: "Romania",
  },
  {
    label: "+1869",
    value: "+1869",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/kn.svg",
    code: "KN",
    name: "Saint Kitts and Nevis",
  },
  {
    label: "+1758",
    value: "+1758",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/lc.svg",
    code: "LC",
    name: "Saint Lucia",
  },
  {
    label: "+1784",
    value: "+1784",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/vc.svg",
    code: "VC",
    name: "Saint Vincent and the Grenadines",
  },
  {
    label: "+685",
    value: "+685",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ws.svg",
    code: "WS",
    name: "Samoa",
  },
  {
    label: "+966",
    value: "+966",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/sa.svg",
    code: "SA",
    name: "Saudi Arabia",
  },
  {
    label: "+381",
    value: "+381",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/rs.svg",
    code: "RS",
    name: "Serbia",
  },
  {
    label: "+65",
    value: "+65",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/sg.svg",
    code: "SG",
    name: "Singapore",
  },
  {
    label: "+421",
    value: "+421",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/sk.svg",
    code: "SK",
    name: "Slovakia",
  },
  {
    label: "+386",
    value: "+386",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/si.svg",
    code: "SI",
    name: "Slovenia",
  },
  {
    label: "+27",
    value: "+27",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/za.svg",
    code: "ZA",
    name: "South Africa",
  },
  {
    label: "+34",
    value: "+34",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/es.svg",
    code: "ES",
    name: "Spain",
  },
  {
    label: "+94",
    value: "+94",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/lk.svg",
    code: "LK",
    name: "Sri Lanka",
  },
  {
    label: "+268",
    value: "+268",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/sz.svg",
    code: "SZ",
    name: "Swaziland",
  },
  {
    label: "+46",
    value: "+46",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/se.svg",
    code: "SE",
    name: "Sweden",
  },
  {
    label: "+41",
    value: "+41",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ch.svg",
    code: "CH",
    name: "Switzerland",
  },
  {
    label: "+963",
    value: "+963",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/sy.svg",
    code: "SY",
    name: "Syrian Arab Republic",
  },
  {
    label: "+886",
    value: "+886",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/tw.svg",
    code: "TW",
    name: "Taiwan, Province of China",
  },
  {
    label: "+992",
    value: "+992",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/tj.svg",
    code: "TJ",
    name: "Tajikistan",
  },
  {
    label: "+255",
    value: "+255",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/tz.svg",
    code: "TZ",
    name: "Tanzania, United Republic of",
  },
  {
    label: "+66",
    value: "+66",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/th.svg",
    code: "TH",
    name: "Thailand",
  },
  {
    label: "+228",
    value: "+228",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/tg.svg",
    code: "TG",
    name: "Togo",
  },
  {
    label: "+1868",
    value: "+1868",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/tt.svg",
    code: "TT",
    name: "Trinidad and Tobago",
  },
  {
    label: "+216",
    value: "+216",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/tn.svg",
    code: "TN",
    name: "Tunisia",
  },
  {
    label: "+90",
    value: "+90",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/tr.svg",
    code: "TR",
    name: "Turkey",
  },
  {
    label: "+993",
    value: "+993",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/tm.svg",
    code: "TM",
    name: "Turkmenistan",
  },
  {
    label: "+1649",
    value: "+1649",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/tc.svg",
    code: "TC",
    name: "Turks and Caicos Islands",
  },
  {
    label: "+688",
    value: "+688",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/tv.svg",
    code: "TV",
    name: "Tuvalu",
  },
  {
    label: "+256",
    value: "+256",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ug.svg",
    code: "UG",
    name: "Uganda",
  },
  {
    label: "+971",
    value: "+971",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ae.svg",
    code: "AE",
    name: "United Arab Emirates",
  },
  {
    label: "+44",
    value: "+44",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/gb.svg",
    code: "GB",
    name: "United Kingdom",
  },
  {
    label: "+1",
    value: "+1",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/us.svg",
    code: "US",
    name: "United States",
  },
  {
    label: "+998",
    value: "+998",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/uz.svg",
    code: "UZ",
    name: "Uzbekistan",
  },
  {
    label: "+678",
    value: "+678",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/vu.svg",
    code: "VU",
    name: "Vanuatu",
  },
  {
    label: "+84",
    value: "+84",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/vn.svg",
    code: "VN",
    name: "Viet Nam",
  },
  {
    label: "+1284",
    value: "+1284",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/vg.svg",
    code: "VG",
    name: "Virgin Islands, British",
  },
  {
    label: "+260",
    value: "+260",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/zm.svg",
    code: "ZM",
    name: "Zambia",
  },
  {
    label: "+263",
    value: "+263",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/zw.svg",
    code: "ZW",
    name: "Zimbabwe",
  },
  {
    label: "+358",
    value: "+358",
    flag: "https://cdn.kcak11.com/CountryFlags/countries/ax.svg",
    code: "AX",
    name: "Åland Islands",
  },
];

export const countryIsoCodes = [
  ...(process.env.NEXT_PUBLIC_NODE_ENV !== "production" ? ["ua"] : []),
  "dz",
  "as",
  "ad",
  "ag",
  "ar",
  "am",
  "aw",
  "au",
  "at",
  "az",
  "bh",
  "bb",
  "be",
  "bz",
  "bj",
  "bm",
  "bt",
  "ba",
  "br",
  "bn",
  "bg",
  "bf",
  "bi",
  "kh",
  "cm",
  "ca",
  "cv",
  "ky",
  "cl",
  "cn",
  "co",
  "ck",
  "cr",
  "ci",
  "hr",
  "cu",
  "cy",
  "cz",
  "dk",
  "dj",
  "dm",
  "do",
  "ec",
  "eg",
  "sv",
  "gq",
  "ee",
  "et",
  "fo",
  "fj",
  "fi",
  "fr",
  "ga",
  "ge",
  "de",
  "gi",
  "gr",
  "gd",
  "gt",
  "gg",
  "gn",
  "hn",
  "hk",
  "hu",
  "is",
  "in",
  "id",
  "ie",
  "im",
  "il",
  "it",
  "jm",
  "jp",
  "je",
  "kz",
  "ke",
  "kw",
  "kg",
  "lv",
  "lb",
  "ls",
  "ly",
  "li",
  "lt",
  "lu",
  "mk",
  "mw",
  "my",
  "mt",
  "mr",
  "mx",
  "md",
  "mc",
  "me",
  "ms",
  "ma",
  "na",
  "np",
  "nl",
  "an",
  "nz",
  "ni",
  "ne",
  "ng",
  "nf",
  "no",
  "om",
  "pk",
  "ps",
  "pa",
  "py",
  "pe",
  "ph",
  "pl",
  "pt",
  "pr",
  "qa",
  "ro",
  "kn",
  "lc",
  "vc",
  "ws",
  "sa",
  "rs",
  "sg",
  "sk",
  "si",
  "za",
  "es",
  "lk",
  "sz",
  "se",
  "ch",
  "sy",
  "tw",
  "tj",
  "tz",
  "th",
  "tg",
  "tt",
  "tn",
  "tr",
  "tm",
  "tc",
  "tv",
  "ug",
  "ae",
  "gb",
  "us",
  "uz",
  "vu",
  "vn",
  "vg",
  "zm",
  "zw",
  "ax",
];
